"""
HoI4-style tech tree node definitions.
Nodes have prerequisites, research costs, and concrete unlocks.
"""
from typing import Optional

# ── Node definitions ──────────────────────────────────────────────────────────
# Each node:
#   id, name, description, branch, column (0-based), row (0-based),
#   requires: list of prerequisite node IDs,
#   cost: research points to unlock,
#   icon: emoji,
#   unlocks: dict of effects applied when researched (same schema as issue effects)
#   unlock_text: human-readable description of what it unlocks

TECH_NODES = [

    # ════════════════════════════════
    #  BRANCH: INFANTRY  (col 0)
    # ════════════════════════════════
    {
        "id": "inf_basic",
        "name": "Basic Infantry Training",
        "description": "Standard drill and rifle marksmanship for all ground forces.",
        "branch": "military",
        "column": 0, "row": 0,
        "requires": [],
        "cost": 30,
        "icon": "🪖",
        "unlocks": {"morale": 0.05, "equipment_level": 0.03},
        "unlock_text": "+5% Morale  ·  +3% Equipment Effectiveness",
    },
    {
        "id": "inf_tactics",
        "name": "Improved Infantry Tactics",
        "description": "Fire-and-movement doctrine, squad-level communications.",
        "branch": "military",
        "column": 0, "row": 1,
        "requires": ["inf_basic"],
        "cost": 60,
        "icon": "📋",
        "unlocks": {"morale": 0.05, "army_size": 20000},
        "unlock_text": "+5% Morale  ·  +20 000 Manpower",
    },
    {
        "id": "inf_elite",
        "name": "Elite Infantry Divisions",
        "description": "Ranger, paratrooper, and commando units. Special operations capability.",
        "branch": "military",
        "column": 0, "row": 2,
        "requires": ["inf_tactics"],
        "cost": 100,
        "icon": "🦅",
        "unlocks": {"morale": 0.08, "equipment_level": 0.05},
        "unlock_text": "+8% Morale  ·  +5% Equipment Level",
    },
    {
        "id": "inf_motorised",
        "name": "Motorised Infantry",
        "description": "Trucks and half-tracks allow infantry to keep pace with armoured advances.",
        "branch": "military",
        "column": 0, "row": 3,
        "requires": ["inf_elite"],
        "cost": 120,
        "icon": "🚛",
        "unlocks": {"morale": 0.05, "war_support": 0.04},
        "unlock_text": "+5% Morale  ·  +4% War Support",
    },

    # ════════════════════════════════
    #  BRANCH: ARMOUR  (col 1)
    # ════════════════════════════════
    {
        "id": "arm_light",
        "name": "Light Tank Programme",
        "description": "Reconnaissance and infantry-support light armoured vehicles.",
        "branch": "military",
        "column": 1, "row": 0,
        "requires": [],
        "cost": 50,
        "icon": "🛡️",
        "unlocks": {"equipment_level": 0.05, "war_support": 0.03},
        "unlock_text": "+5% Equipment Level  ·  +3% War Support",
    },
    {
        "id": "arm_medium",
        "name": "Medium Tank Doctrine",
        "description": "Main battle tanks capable of offensive and defensive operations.",
        "branch": "military",
        "column": 1, "row": 1,
        "requires": ["arm_light"],
        "cost": 90,
        "icon": "🔩",
        "unlocks": {"equipment_level": 0.08, "morale": 0.04},
        "unlock_text": "+8% Equipment Level  ·  +4% Morale",
    },
    {
        "id": "arm_heavy",
        "name": "Heavy Tank Programme",
        "description": "Breakthrough armour — fearsome in assault, resource-intensive to maintain.",
        "branch": "military",
        "column": 1, "row": 2,
        "requires": ["arm_medium"],
        "cost": 140,
        "icon": "⚙️",
        "unlocks": {"equipment_level": 0.10, "war_support": 0.05},
        "unlock_text": "+10% Equipment Level  ·  +5% War Support",
    },
    {
        "id": "arm_blitz",
        "name": "Blitzkrieg Doctrine",
        "description": "Combined arms coordination: tanks, infantry, and air power as one weapon.",
        "branch": "military",
        "column": 1, "row": 3,
        "requires": ["arm_heavy", "air_fighters"],
        "cost": 180,
        "icon": "⚡",
        "unlocks": {"equipment_level": 0.08, "morale": 0.08, "war_support": 0.06},
        "unlock_text": "+8% Equip  ·  +8% Morale  ·  +6% War Support",
    },

    # ════════════════════════════════
    #  BRANCH: AIR POWER  (col 2)
    # ════════════════════════════════
    {
        "id": "air_basic",
        "name": "Basic Air Force",
        "description": "Biplane and early monoplane reconnaissance and observation aircraft.",
        "branch": "military",
        "column": 2, "row": 0,
        "requires": [],
        "cost": 40,
        "icon": "✈️",
        "unlocks": {"war_support": 0.03, "prestige": 5},
        "unlock_text": "+3% War Support  ·  +5 Prestige",
    },
    {
        "id": "air_fighters",
        "name": "Fighter Aviation",
        "description": "Dedicated air superiority fighters contest control of the skies.",
        "branch": "military",
        "column": 2, "row": 1,
        "requires": ["air_basic"],
        "cost": 80,
        "icon": "🛩️",
        "unlocks": {"war_support": 0.06, "morale": 0.03},
        "unlock_text": "+6% War Support  ·  +3% Morale",
    },
    {
        "id": "air_cas",
        "name": "Close Air Support",
        "description": "Ground attack aircraft directly support infantry and armour in battle.",
        "branch": "military",
        "column": 2, "row": 2,
        "requires": ["air_fighters"],
        "cost": 110,
        "icon": "💣",
        "unlocks": {"equipment_level": 0.06, "war_support": 0.05},
        "unlock_text": "+6% Equip Effectiveness  ·  +5% War Support",
    },
    {
        "id": "air_strategic",
        "name": "Strategic Bombing",
        "description": "Long-range bombers strike enemy industry, railways, and cities.",
        "branch": "military",
        "column": 2, "row": 3,
        "requires": ["air_cas"],
        "cost": 160,
        "icon": "🏭",
        "unlocks": {"war_support": 0.08, "prestige": 8},
        "unlock_text": "+8% War Support  ·  +8 Prestige  (enemy GDP hit in war)",
    },

    # ════════════════════════════════
    #  BRANCH: NAVAL  (col 3)
    # ════════════════════════════════
    {
        "id": "nav_basic",
        "name": "Basic Naval Force",
        "description": "Patrol vessels, coastal defence guns, and harbour infrastructure.",
        "branch": "military",
        "column": 3, "row": 0,
        "requires": [],
        "cost": 35,
        "icon": "⚓",
        "unlocks": {"war_support": 0.02, "prestige": 3},
        "unlock_text": "+2% War Support  ·  +3 Prestige",
    },
    {
        "id": "nav_destroyers",
        "name": "Destroyer Flotilla",
        "description": "Fast escort vessels protect trade lanes from submarines.",
        "branch": "military",
        "column": 3, "row": 1,
        "requires": ["nav_basic"],
        "cost": 70,
        "icon": "🚢",
        "unlocks": {"war_support": 0.05, "gdp_growth": 0.005},
        "unlock_text": "+5% War Support  ·  Trade protection (+0.5% GDP growth)",
    },
    {
        "id": "nav_capital",
        "name": "Capital Ships",
        "description": "Cruisers and battleships project naval power across oceans.",
        "branch": "military",
        "column": 3, "row": 2,
        "requires": ["nav_destroyers"],
        "cost": 130,
        "icon": "🛳️",
        "unlocks": {"prestige": 15, "war_support": 0.06},
        "unlock_text": "+15 Prestige  ·  +6% War Support",
    },
    {
        "id": "nav_carriers",
        "name": "Carrier Strike Groups",
        "description": "Aircraft carriers extend air power to any ocean in the world.",
        "branch": "military",
        "column": 3, "row": 3,
        "requires": ["nav_capital", "air_fighters"],
        "cost": 200,
        "icon": "🏗️",
        "unlocks": {"prestige": 20, "war_support": 0.10},
        "unlock_text": "+20 Prestige  ·  +10% War Support",
    },

    # ════════════════════════════════
    #  BRANCH: INDUSTRY  (col 4)
    # ════════════════════════════════
    {
        "id": "ind_basic",
        "name": "Industrial Foundation",
        "description": "Steam power, mechanised production lines, standardised measurements.",
        "branch": "industry",
        "column": 4, "row": 0,
        "requires": [],
        "cost": 25,
        "icon": "🏭",
        "unlocks": {"gdp_growth": 0.008, "factories": 2},
        "unlock_text": "+0.8% GDP Growth  ·  +2 Civilian Factories",
    },
    {
        "id": "ind_mass",
        "name": "Mass Production",
        "description": "Assembly lines and interchangeable parts slash unit costs.",
        "branch": "industry",
        "column": 4, "row": 1,
        "requires": ["ind_basic"],
        "cost": 60,
        "icon": "⚙️",
        "unlocks": {"gdp_growth": 0.010, "arms_factories": 2},
        "unlock_text": "+1% GDP Growth  ·  +2 Arms Factories",
    },
    {
        "id": "ind_war_eco",
        "name": "War Economy",
        "description": "Total mobilisation of industry for military output.",
        "branch": "industry",
        "column": 4, "row": 2,
        "requires": ["ind_mass"],
        "cost": 90,
        "icon": "⚔️",
        "unlocks": {"arms_factories": 3, "war_support": 0.05, "gdp_growth": 0.005},
        "unlock_text": "+3 Arms Factories  ·  +5% War Support  ·  +0.5% GDP",
    },
    {
        "id": "ind_synthetic",
        "name": "Synthetic Resources",
        "description": "Produce synthetic fuel, rubber, and steel from coal and air — end resource dependency.",
        "branch": "industry",
        "column": 4, "row": 3,
        "requires": ["ind_war_eco"],
        "cost": 140,
        "icon": "🧪",
        "unlocks": {"gdp_growth": 0.012, "unemployment": -0.01},
        "unlock_text": "+1.2% GDP Growth  ·  −1% Unemployment  (resource independence)",
    },

    # ════════════════════════════════
    #  BRANCH: RESEARCH  (col 5)
    # ════════════════════════════════
    {
        "id": "res_labs",
        "name": "Research Laboratories",
        "description": "State-funded universities and applied science institutes.",
        "branch": "industry",
        "column": 5, "row": 0,
        "requires": [],
        "cost": 30,
        "icon": "🔬",
        "unlocks": {"research_labs": 1, "research_points": 15},
        "unlock_text": "+1 Research Lab  ·  +15 Research Points",
    },
    {
        "id": "res_applied",
        "name": "Applied Science Programme",
        "description": "Government grants direct research toward military and industrial goals.",
        "branch": "industry",
        "column": 5, "row": 1,
        "requires": ["res_labs"],
        "cost": 70,
        "icon": "📐",
        "unlocks": {"research_labs": 1, "research_points": 25, "research_slots": 1},
        "unlock_text": "+1 Research Lab  ·  +25 Research Points  ·  +1 Research Slot",
    },
    {
        "id": "res_atomic",
        "name": "Nuclear Research",
        "description": "Theoretical and applied nuclear physics — gateway to atomic power.",
        "branch": "industry",
        "column": 5, "row": 2,
        "requires": ["res_applied"],
        "cost": 150,
        "icon": "⚛️",
        "unlocks": {"research_points": 50, "prestige": 12},
        "unlock_text": "+50 Research Points  ·  +12 Prestige",
    },
    {
        "id": "res_computing",
        "name": "Early Computing",
        "description": "Mechanical and later electronic computation improves logistics and codebreaking.",
        "branch": "industry",
        "column": 5, "row": 3,
        "requires": ["res_atomic"],
        "cost": 180,
        "icon": "💻",
        "unlocks": {"research_points": 40, "gdp_growth": 0.010},
        "unlock_text": "+40 Research Points  ·  +1% GDP Growth",
    },

    # ════════════════════════════════
    #  BRANCH: DIPLOMACY  (col 6)
    # ════════════════════════════════
    {
        "id": "dip_network",
        "name": "Diplomatic Network",
        "description": "Embassies, consulates, and trained attachés across the world.",
        "branch": "diplomacy",
        "column": 6, "row": 0,
        "requires": [],
        "cost": 20,
        "icon": "🌐",
        "unlocks": {"prestige": 6, "stability": 0.02},
        "unlock_text": "+6 Prestige  ·  +2% Stability",
    },
    {
        "id": "dip_trade",
        "name": "Trade Agreements",
        "description": "Negotiated preferential tariffs and most-favoured-nation clauses.",
        "branch": "diplomacy",
        "column": 6, "row": 1,
        "requires": ["dip_network"],
        "cost": 50,
        "icon": "🤝",
        "unlocks": {"gdp_growth": 0.012, "trade_openness": 0.05},
        "unlock_text": "+1.2% GDP Growth  ·  +5% Trade Openness",
    },
    {
        "id": "dip_intel",
        "name": "Intelligence Service",
        "description": "SIGINT, HUMINT, and covert operations capability.",
        "branch": "diplomacy",
        "column": 6, "row": 2,
        "requires": ["dip_trade"],
        "cost": 90,
        "icon": "🕵️",
        "unlocks": {"stability": 0.03, "prestige": 8},
        "unlock_text": "+3% Stability  ·  +8 Prestige",
    },
    {
        "id": "dip_propaganda",
        "name": "Propaganda & Media",
        "description": "State messaging shapes public opinion at home and soft power abroad.",
        "branch": "diplomacy",
        "column": 6, "row": 3,
        "requires": ["dip_intel"],
        "cost": 110,
        "icon": "📻",
        "unlocks": {"war_support": 0.06, "happiness": 0.04, "stability": 0.02},
        "unlock_text": "+6% War Support  ·  +4% Happiness  ·  +2% Stability",
    },

    # ════════════════════════════════
    #  BRANCH: ECONOMY  (col 7)
    # ════════════════════════════════
    {
        "id": "eco_banking",
        "name": "Central Banking",
        "description": "A central bank stabilises currency and enables monetary policy.",
        "branch": "diplomacy",
        "column": 7, "row": 0,
        "requires": [],
        "cost": 25,
        "icon": "🏦",
        "unlocks": {"inflation": -0.01, "gdp_growth": 0.005},
        "unlock_text": "−1% Inflation  ·  +0.5% GDP Growth",
    },
    {
        "id": "eco_welfare",
        "name": "Social Welfare System",
        "description": "Unemployment insurance, pensions, and healthcare improve stability.",
        "branch": "diplomacy",
        "column": 7, "row": 1,
        "requires": ["eco_banking"],
        "cost": 60,
        "icon": "🏥",
        "unlocks": {"stability": 0.04, "happiness": 0.06, "unemployment": -0.01},
        "unlock_text": "+4% Stability  ·  +6% Happiness  ·  −1% Unemployment",
    },
    {
        "id": "eco_keynesian",
        "name": "Keynesian Stimulus",
        "description": "Counter-cyclical spending smooths economic cycles and prevents recessions.",
        "branch": "diplomacy",
        "column": 7, "row": 2,
        "requires": ["eco_welfare"],
        "cost": 90,
        "icon": "📈",
        "unlocks": {"gdp_growth": 0.015, "unemployment": -0.02},
        "unlock_text": "+1.5% GDP Growth  ·  −2% Unemployment",
    },
    {
        "id": "eco_globalisation",
        "name": "Globalisation",
        "description": "Open markets, multinational investment, and integrated supply chains.",
        "branch": "diplomacy",
        "column": 7, "row": 3,
        "requires": ["eco_keynesian", "dip_trade"],
        "cost": 150,
        "icon": "🌏",
        "unlocks": {"gdp_growth": 0.020, "trade_openness": 0.10, "prestige": 10},
        "unlock_text": "+2% GDP Growth  ·  +10% Trade Openness  ·  +10 Prestige",
    },

    # ════════════════════════════════
    #  EXPANDED TECHS (ERA-SPECIFIC)
    # ════════════════════════════════
    {
        "id": "inf_swordsmanship",
        "name": "Sword & Pike Drills",
        "description": "Structured melee formations and disciplined infantry lines.",
        "branch": "military",
        "column": 0, "row": 4,
        "requires": [],
        "cost": 15,
        "era_years": [(1600, 1830)],
        "icon": "⚔️",
        "unlocks": {"morale": 0.03, "war_support": 0.02},
        "unlock_text": "+3% Morale  ·  +2% War Support",
    },
    {
        "id": "inf_castle_forts",
        "name": "Castle Fortifications",
        "description": "Stone keeps, city walls, and layered defenses slow invasions.",
        "branch": "military",
        "column": 0, "row": 5,
        "requires": ["inf_swordsmanship"],
        "cost": 25,
        "era_years": [(1600, 1830)],
        "icon": "🏰",
        "unlocks": {"stability": 0.02, "war_support": 0.02},
        "unlock_text": "+2% Stability  ·  +2% War Support",
    },
    {
        "id": "inf_bayonet_drill",
        "name": "Bayonet Drill",
        "description": "Line infantry drills for volley fire and bayonet charges.",
        "branch": "military",
        "column": 0, "row": 6,
        "requires": ["inf_basic"],
        "cost": 40,
        "era_years": [(1815, 1890)],
        "icon": "🔫",
        "unlocks": {"morale": 0.04, "army_size": 10000},
        "unlock_text": "+4% Morale  ·  +10 000 Manpower",
    },
    {
        "id": "inf_rifled_muskets",
        "name": "Rifled Muskets",
        "description": "Grooved barrels improve accuracy and range.",
        "branch": "military",
        "column": 0, "row": 7,
        "requires": ["inf_bayonet_drill"],
        "cost": 55,
        "era_years": [(1815, 1890)],
        "icon": "🎯",
        "unlocks": {"equipment_level": 0.04, "war_support": 0.03},
        "unlock_text": "+4% Equipment Level  ·  +3% War Support",
    },
    {
        "id": "inf_trench_warfare",
        "name": "Trench Warfare",
        "description": "Field entrenchment, barbed wire, and artillery coordination.",
        "branch": "military",
        "column": 0, "row": 8,
        "requires": ["inf_rifled_muskets"],
        "cost": 75,
        "era_years": [(1890, 1945)],
        "icon": "🧱",
        "unlocks": {"morale": 0.05, "stability": 0.02},
        "unlock_text": "+5% Morale  ·  +2% Stability",
    },
    {
        "id": "inf_assault_rifles",
        "name": "Assault Rifles",
        "description": "Selective-fire rifles raise infantry firepower and flexibility.",
        "branch": "military",
        "column": 0, "row": 9,
        "requires": ["inf_trench_warfare"],
        "cost": 95,
        "era_years": [(1940, 2060)],
        "icon": "💥",
        "unlocks": {"equipment_level": 0.06, "morale": 0.04},
        "unlock_text": "+6% Equipment Level  ·  +4% Morale",
    },
    {
        "id": "inf_mechanized",
        "name": "Mechanized Infantry",
        "description": "Infantry fighting vehicles combine mobility and protection.",
        "branch": "military",
        "column": 0, "row": 10,
        "requires": ["inf_motorised"],
        "cost": 120,
        "era_years": [(1940, 2060)],
        "icon": "🛞",
        "unlocks": {"morale": 0.06, "war_support": 0.04},
        "unlock_text": "+6% Morale  ·  +4% War Support",
    },
    {
        "id": "inf_night_vision",
        "name": "Night Vision Optics",
        "description": "Infrared and low-light optics enable round-the-clock operations.",
        "branch": "military",
        "column": 0, "row": 11,
        "requires": ["inf_assault_rifles"],
        "cost": 135,
        "era_years": [(1960, 2060)],
        "icon": "🌙",
        "unlocks": {"morale": 0.05, "equipment_level": 0.04},
        "unlock_text": "+5% Morale  ·  +4% Equipment Level",
    },
    {
        "id": "inf_networked",
        "name": "Networked Command",
        "description": "Digitized comms and battlefield data links improve coordination.",
        "branch": "military",
        "column": 0, "row": 12,
        "requires": ["inf_night_vision"],
        "cost": 160,
        "era_years": [(1990, 2060)],
        "icon": "🛰️",
        "unlocks": {"morale": 0.06, "war_support": 0.03},
        "unlock_text": "+6% Morale  ·  +3% War Support",
    },
    {
        "id": "inf_drone_integration",
        "name": "Tactical Drone Integration",
        "description": "Small UAVs for recon and targeting at unit level.",
        "branch": "military",
        "column": 0, "row": 13,
        "requires": ["inf_networked"],
        "cost": 190,
        "era_years": [(2010, 2060)],
        "icon": "🛸",
        "unlocks": {"equipment_level": 0.07, "war_support": 0.04},
        "unlock_text": "+7% Equipment Level  ·  +4% War Support",
    },

    {
        "id": "arm_armored_cars",
        "name": "Armored Cars",
        "description": "Early armored vehicles for scouting and rapid response.",
        "branch": "military",
        "column": 1, "row": 4,
        "requires": ["arm_light"],
        "cost": 70,
        "era_years": [(1900, 1945)],
        "icon": "🚙",
        "unlocks": {"equipment_level": 0.04, "war_support": 0.03},
        "unlock_text": "+4% Equipment Level  ·  +3% War Support",
    },
    {
        "id": "arm_tank_destroyers",
        "name": "Tank Destroyers",
        "description": "Specialized anti-armor vehicles counter heavy tanks.",
        "branch": "military",
        "column": 1, "row": 5,
        "requires": ["arm_medium"],
        "cost": 110,
        "era_years": [(1930, 1970)],
        "icon": "🛡️",
        "unlocks": {"equipment_level": 0.05, "morale": 0.03},
        "unlock_text": "+5% Equipment Level  ·  +3% Morale",
    },
    {
        "id": "arm_mbt",
        "name": "Main Battle Tank",
        "description": "Unified tank design for breakthrough and defense roles.",
        "branch": "military",
        "column": 1, "row": 6,
        "requires": ["arm_heavy"],
        "cost": 160,
        "era_years": [(1945, 2060)],
        "icon": "🛡️",
        "unlocks": {"equipment_level": 0.08, "morale": 0.04},
        "unlock_text": "+8% Equipment Level  ·  +4% Morale",
    },
    {
        "id": "arm_reactive_armor",
        "name": "Reactive Armor",
        "description": "Explosive reactive armor improves survivability.",
        "branch": "military",
        "column": 1, "row": 7,
        "requires": ["arm_mbt"],
        "cost": 180,
        "era_years": [(1960, 2060)],
        "icon": "🧱",
        "unlocks": {"equipment_level": 0.07, "morale": 0.03},
        "unlock_text": "+7% Equipment Level  ·  +3% Morale",
    },
    {
        "id": "arm_active_protection",
        "name": "Active Protection Systems",
        "description": "Radar-guided interceptors neutralize incoming threats.",
        "branch": "military",
        "column": 1, "row": 8,
        "requires": ["arm_reactive_armor"],
        "cost": 210,
        "era_years": [(1990, 2060)],
        "icon": "🛡️",
        "unlocks": {"equipment_level": 0.08, "war_support": 0.03},
        "unlock_text": "+8% Equipment Level  ·  +3% War Support",
    },
    {
        "id": "arm_autonomous_armor",
        "name": "Autonomous Armor",
        "description": "Semi-autonomous vehicle control reduces crew losses.",
        "branch": "military",
        "column": 1, "row": 9,
        "requires": ["arm_active_protection"],
        "cost": 240,
        "era_years": [(2030, 2060)],
        "icon": "🤖",
        "unlocks": {"equipment_level": 0.09, "morale": 0.04},
        "unlock_text": "+9% Equipment Level  ·  +4% Morale",
    },

    {
        "id": "air_prop_bombers",
        "name": "Propeller Bombers",
        "description": "Medium-range bombers for tactical and strategic roles.",
        "branch": "military",
        "column": 2, "row": 4,
        "requires": ["air_basic"],
        "cost": 90,
        "era_years": [(1910, 1945)],
        "icon": "✈️",
        "unlocks": {"war_support": 0.05, "prestige": 5},
        "unlock_text": "+5% War Support  ·  +5 Prestige",
    },
    {
        "id": "air_airlift",
        "name": "Strategic Airlift",
        "description": "Transport aircraft enable rapid deployment across theaters.",
        "branch": "military",
        "column": 2, "row": 5,
        "requires": ["air_basic"],
        "cost": 100,
        "era_years": [(1940, 2060)],
        "icon": "🧳",
        "unlocks": {"morale": 0.03, "war_support": 0.03},
        "unlock_text": "+3% Morale  ·  +3% War Support",
    },
    {
        "id": "air_jet_fighters",
        "name": "Jet Fighters",
        "description": "High-speed fighters dominate post-war skies.",
        "branch": "military",
        "column": 2, "row": 6,
        "requires": ["air_fighters"],
        "cost": 140,
        "era_years": [(1945, 2060)],
        "icon": "🛩️",
        "unlocks": {"war_support": 0.06, "morale": 0.04},
        "unlock_text": "+6% War Support  ·  +4% Morale",
    },
    {
        "id": "air_jet_bombers",
        "name": "Jet Bombers",
        "description": "Long-range jet bombers extend strategic reach.",
        "branch": "military",
        "column": 2, "row": 7,
        "requires": ["air_strategic"],
        "cost": 170,
        "era_years": [(1945, 2060)],
        "icon": "💥",
        "unlocks": {"war_support": 0.07, "prestige": 8},
        "unlock_text": "+7% War Support  ·  +8 Prestige",
    },
    {
        "id": "air_awacs",
        "name": "Airborne Early Warning",
        "description": "Radar aircraft coordinate air defense and interception.",
        "branch": "military",
        "column": 2, "row": 8,
        "requires": ["air_jet_fighters"],
        "cost": 180,
        "era_years": [(1960, 2060)],
        "icon": "📡",
        "unlocks": {"morale": 0.04, "war_support": 0.04},
        "unlock_text": "+4% Morale  ·  +4% War Support",
    },
    {
        "id": "air_stealth",
        "name": "Stealth Aircraft",
        "description": "Low-observable airframes evade radar detection.",
        "branch": "military",
        "column": 2, "row": 9,
        "requires": ["air_jet_bombers"],
        "cost": 210,
        "era_years": [(1985, 2060)],
        "icon": "🕶️",
        "unlocks": {"war_support": 0.06, "prestige": 10},
        "unlock_text": "+6% War Support  ·  +10 Prestige",
    },
    {
        "id": "air_drones",
        "name": "Unmanned Aerial Systems",
        "description": "Persistent surveillance and precision strike drones.",
        "branch": "military",
        "column": 2, "row": 10,
        "requires": ["air_awacs"],
        "cost": 230,
        "era_years": [(2000, 2060)],
        "icon": "🛸",
        "unlocks": {"equipment_level": 0.05, "war_support": 0.04},
        "unlock_text": "+5% Equipment Level  ·  +4% War Support",
    },

    {
        "id": "nav_ironclads",
        "name": "Ironclads",
        "description": "Armored steamships with heavy guns.",
        "branch": "military",
        "column": 3, "row": 4,
        "requires": ["nav_basic"],
        "cost": 60,
        "era_years": [(1815, 1890)],
        "icon": "🛳️",
        "unlocks": {"prestige": 6, "war_support": 0.03},
        "unlock_text": "+6 Prestige  ·  +3% War Support",
    },
    {
        "id": "nav_dreadnoughts",
        "name": "Dreadnoughts",
        "description": "All-big-gun battleships dominate naval warfare.",
        "branch": "military",
        "column": 3, "row": 5,
        "requires": ["nav_capital"],
        "cost": 120,
        "era_years": [(1890, 1945)],
        "icon": "🚢",
        "unlocks": {"prestige": 10, "war_support": 0.05},
        "unlock_text": "+10 Prestige  ·  +5% War Support",
    },
    {
        "id": "nav_submarines",
        "name": "Submarine Warfare",
        "description": "Stealthy underwater fleets threaten trade lanes.",
        "branch": "military",
        "column": 3, "row": 6,
        "requires": ["nav_destroyers"],
        "cost": 110,
        "era_years": [(1910, 2060)],
        "icon": "🫧",
        "unlocks": {"war_support": 0.04, "gdp_growth": 0.004},
        "unlock_text": "+4% War Support  ·  +0.4% GDP Growth",
    },
    {
        "id": "nav_amphibious",
        "name": "Amphibious Doctrine",
        "description": "Landing craft and logistics for overseas invasions.",
        "branch": "military",
        "column": 3, "row": 7,
        "requires": ["nav_basic"],
        "cost": 100,
        "era_years": [(1910, 2060)],
        "icon": "🪖",
        "unlocks": {"war_support": 0.04, "prestige": 4},
        "unlock_text": "+4% War Support  ·  +4 Prestige",
    },
    {
        "id": "nav_nuclear_subs",
        "name": "Nuclear Submarines",
        "description": "Long-endurance subs with strategic deterrent roles.",
        "branch": "military",
        "column": 3, "row": 8,
        "requires": ["nav_submarines"],
        "cost": 190,
        "era_years": [(1955, 2060)],
        "icon": "☢️",
        "unlocks": {"prestige": 12, "war_support": 0.05},
        "unlock_text": "+12 Prestige  ·  +5% War Support",
    },
    {
        "id": "nav_missile_cruisers",
        "name": "Missile Cruisers",
        "description": "Guided missiles extend naval strike range.",
        "branch": "military",
        "column": 3, "row": 9,
        "requires": ["nav_capital"],
        "cost": 170,
        "era_years": [(1960, 2060)],
        "icon": "🚀",
        "unlocks": {"prestige": 10, "war_support": 0.05},
        "unlock_text": "+10 Prestige  ·  +5% War Support",
    },
    {
        "id": "nav_aegis",
        "name": "Integrated Air Defense Fleet",
        "description": "Networked radar and interceptors protect carrier groups.",
        "branch": "military",
        "column": 3, "row": 10,
        "requires": ["nav_missile_cruisers"],
        "cost": 210,
        "era_years": [(1980, 2060)],
        "icon": "🛰️",
        "unlocks": {"war_support": 0.05, "prestige": 8},
        "unlock_text": "+5% War Support  ·  +8 Prestige",
    },
    {
        "id": "nav_supercarriers",
        "name": "Supercarriers",
        "description": "Large deck carriers project massive air power.",
        "branch": "military",
        "column": 3, "row": 11,
        "requires": ["nav_carriers"],
        "cost": 230,
        "era_years": [(1980, 2060)],
        "icon": "🛳️",
        "unlocks": {"prestige": 14, "war_support": 0.06},
        "unlock_text": "+14 Prestige  ·  +6% War Support",
    },

    {
        "id": "ind_canals",
        "name": "Canal Networks",
        "description": "Canals and inland waterways reduce transport costs.",
        "branch": "industry",
        "column": 4, "row": 4,
        "requires": ["ind_basic"],
        "cost": 40,
        "era_years": [(1815, 1890)],
        "icon": "🚤",
        "unlocks": {"gdp_growth": 0.006, "trade_openness": 0.02},
        "unlock_text": "+0.6% GDP Growth  ·  +2% Trade Openness",
    },
    {
        "id": "ind_railways",
        "name": "National Railways",
        "description": "Rail grids integrate markets and mobilize industry.",
        "branch": "industry",
        "column": 4, "row": 5,
        "requires": ["ind_canals"],
        "cost": 60,
        "era_years": [(1830, 1930)],
        "icon": "🚂",
        "unlocks": {"gdp_growth": 0.010, "factories": 2},
        "unlock_text": "+1% GDP Growth  ·  +2 Factories",
    },
    {
        "id": "ind_electrification",
        "name": "Electrification",
        "description": "Power grids and electric motors modernize production.",
        "branch": "industry",
        "column": 4, "row": 6,
        "requires": ["ind_railways"],
        "cost": 80,
        "era_years": [(1880, 1945)],
        "icon": "⚡",
        "unlocks": {"gdp_growth": 0.012, "arms_factories": 1},
        "unlock_text": "+1.2% GDP Growth  ·  +1 Arms Factory",
    },
    {
        "id": "ind_oil_refining",
        "name": "Oil Refining",
        "description": "Refineries enable fuel stockpiles and mechanization.",
        "branch": "industry",
        "column": 4, "row": 7,
        "requires": ["ind_mass"],
        "cost": 90,
        "era_years": [(1890, 1950)],
        "icon": "🛢️",
        "unlocks": {"gdp_growth": 0.010, "unemployment": -0.005},
        "unlock_text": "+1% GDP Growth  ·  −0.5% Unemployment",
    },
    {
        "id": "ind_automation",
        "name": "Industrial Automation",
        "description": "Robotics and control systems boost output.",
        "branch": "industry",
        "column": 4, "row": 8,
        "requires": ["ind_synthetic"],
        "cost": 140,
        "era_years": [(1950, 2060)],
        "icon": "🤖",
        "unlocks": {"gdp_growth": 0.014, "unemployment": -0.006},
        "unlock_text": "+1.4% GDP Growth  ·  −0.6% Unemployment",
    },
    {
        "id": "ind_microelectronics",
        "name": "Microelectronics",
        "description": "Semiconductors drive advanced manufacturing.",
        "branch": "industry",
        "column": 4, "row": 9,
        "requires": ["ind_automation"],
        "cost": 160,
        "era_years": [(1970, 2060)],
        "icon": "🧩",
        "unlocks": {"gdp_growth": 0.012, "factories": 2},
        "unlock_text": "+1.2% GDP Growth  ·  +2 Factories",
    },
    {
        "id": "ind_composites",
        "name": "Composite Materials",
        "description": "Advanced materials reduce weight and increase strength.",
        "branch": "industry",
        "column": 4, "row": 10,
        "requires": ["ind_microelectronics"],
        "cost": 175,
        "era_years": [(1980, 2060)],
        "icon": "🧪",
        "unlocks": {"gdp_growth": 0.010, "prestige": 6},
        "unlock_text": "+1% GDP Growth  ·  +6 Prestige",
    },
    {
        "id": "ind_green_energy",
        "name": "Green Energy",
        "description": "Renewables and storage stabilize long-term supply.",
        "branch": "industry",
        "column": 4, "row": 11,
        "requires": ["ind_composites"],
        "cost": 190,
        "era_years": [(2000, 2060)],
        "icon": "🌿",
        "unlocks": {"gdp_growth": 0.008, "stability": 0.02},
        "unlock_text": "+0.8% GDP Growth  ·  +2% Stability",
    },
    {
        "id": "ind_space_industry",
        "name": "Space Industry",
        "description": "Launch infrastructure and orbital manufacturing.",
        "branch": "industry",
        "column": 4, "row": 12,
        "requires": ["ind_composites"],
        "cost": 220,
        "era_years": [(2030, 2060)],
        "icon": "🚀",
        "unlocks": {"prestige": 12, "gdp_growth": 0.010},
        "unlock_text": "+12 Prestige  ·  +1% GDP Growth",
    },

    {
        "id": "res_radar",
        "name": "Radar",
        "description": "Radio detection improves air defense and naval awareness.",
        "branch": "industry",
        "column": 5, "row": 4,
        "requires": ["res_labs"],
        "cost": 90,
        "era_years": [(1935, 1965)],
        "icon": "📡",
        "unlocks": {"war_support": 0.03, "prestige": 4},
        "unlock_text": "+3% War Support  ·  +4 Prestige",
    },
    {
        "id": "res_rocketry",
        "name": "Rocketry",
        "description": "Ballistic research opens new strategic weapons.",
        "branch": "industry",
        "column": 5, "row": 5,
        "requires": ["res_applied"],
        "cost": 120,
        "era_years": [(1935, 2060)],
        "icon": "🚀",
        "unlocks": {"prestige": 6, "war_support": 0.04},
        "unlock_text": "+6 Prestige  ·  +4% War Support",
    },
    {
        "id": "res_satellites",
        "name": "Satellites",
        "description": "Orbital platforms enable surveillance and communications.",
        "branch": "industry",
        "column": 5, "row": 6,
        "requires": ["res_rocketry"],
        "cost": 160,
        "era_years": [(1957, 2060)],
        "icon": "🛰️",
        "unlocks": {"prestige": 10, "stability": 0.02},
        "unlock_text": "+10 Prestige  ·  +2% Stability",
    },
    {
        "id": "res_internet",
        "name": "Internet Infrastructure",
        "description": "Global networks accelerate commerce and coordination.",
        "branch": "industry",
        "column": 5, "row": 7,
        "requires": ["res_computing"],
        "cost": 170,
        "era_years": [(1980, 2060)],
        "icon": "🌐",
        "unlocks": {"gdp_growth": 0.010, "prestige": 6},
        "unlock_text": "+1% GDP Growth  ·  +6 Prestige",
    },
    {
        "id": "res_biotech",
        "name": "Biotechnology",
        "description": "Medical and agricultural breakthroughs boost resilience.",
        "branch": "industry",
        "column": 5, "row": 8,
        "requires": ["res_computing"],
        "cost": 150,
        "era_years": [(1990, 2060)],
        "icon": "🧬",
        "unlocks": {"happiness": 0.03, "stability": 0.02},
        "unlock_text": "+3% Happiness  ·  +2% Stability",
    },
    {
        "id": "res_ai",
        "name": "Artificial Intelligence",
        "description": "Machine learning enhances logistics and decision-making.",
        "branch": "industry",
        "column": 5, "row": 9,
        "requires": ["res_internet"],
        "cost": 200,
        "era_years": [(2000, 2060)],
        "icon": "🤖",
        "unlocks": {"gdp_growth": 0.012, "prestige": 8},
        "unlock_text": "+1.2% GDP Growth  ·  +8 Prestige",
    },
    {
        "id": "res_quantum",
        "name": "Quantum Computing",
        "description": "Quantum breakthroughs unlock new strategic capabilities.",
        "branch": "industry",
        "column": 5, "row": 10,
        "requires": ["res_ai"],
        "cost": 240,
        "era_years": [(2015, 2060)],
        "icon": "⚛️",
        "unlocks": {"prestige": 12, "stability": 0.02},
        "unlock_text": "+12 Prestige  ·  +2% Stability",
    },

    {
        "id": "dip_non_aggression",
        "name": "Non-Aggression Pacts",
        "description": "Formal agreements reduce the risk of surprise war.",
        "branch": "diplomacy",
        "column": 6, "row": 4,
        "requires": ["dip_network"],
        "cost": 45,
        "era_years": [(1815, 2060)],
        "icon": "🕊️",
        "unlocks": {"stability": 0.02, "prestige": 3},
        "unlock_text": "+2% Stability  ·  +3 Prestige",
    },
    {
        "id": "dip_defense_pacts",
        "name": "Defense Pact Frameworks",
        "description": "Standardized treaties enable rapid mutual defense.",
        "branch": "diplomacy",
        "column": 6, "row": 5,
        "requires": ["dip_non_aggression"],
        "cost": 75,
        "era_years": [(1910, 2060)],
        "icon": "🛡️",
        "unlocks": {"prestige": 5, "war_support": 0.03},
        "unlock_text": "+5 Prestige  ·  +3% War Support",
    },
    {
        "id": "dip_alliance_blocs",
        "name": "Alliance Blocs",
        "description": "Multi-nation defense structures deepen commitments.",
        "branch": "diplomacy",
        "column": 6, "row": 6,
        "requires": ["dip_defense_pacts"],
        "cost": 110,
        "era_years": [(1930, 2060)],
        "icon": "🤝",
        "unlocks": {"prestige": 8, "war_support": 0.04},
        "unlock_text": "+8 Prestige  ·  +4% War Support",
    },
    {
        "id": "dip_sanctions_regime",
        "name": "Sanctions Regime",
        "description": "Coordinated economic pressure tools.",
        "branch": "diplomacy",
        "column": 6, "row": 7,
        "requires": ["dip_intel"],
        "cost": 120,
        "era_years": [(1930, 2060)],
        "icon": "⛔",
        "unlocks": {"prestige": 6, "stability": 0.01},
        "unlock_text": "+6 Prestige  ·  +1% Stability",
    },
    {
        "id": "dip_peacekeeping",
        "name": "Peacekeeping Doctrine",
        "description": "Multilateral missions stabilize conflict zones.",
        "branch": "diplomacy",
        "column": 6, "row": 8,
        "requires": ["dip_trade"],
        "cost": 100,
        "era_years": [(1945, 2060)],
        "icon": "🕊️",
        "unlocks": {"prestige": 10, "stability": 0.02},
        "unlock_text": "+10 Prestige  ·  +2% Stability",
    },
    {
        "id": "dip_backchannel",
        "name": "Backchannel Diplomacy",
        "description": "Secret communications avert crises.",
        "branch": "diplomacy",
        "column": 6, "row": 9,
        "requires": ["dip_intel"],
        "cost": 130,
        "era_years": [(1960, 2060)],
        "icon": "📨",
        "unlocks": {"stability": 0.02, "prestige": 6},
        "unlock_text": "+2% Stability  ·  +6 Prestige",
    },
    {
        "id": "dip_cyber_influence",
        "name": "Cyber Influence",
        "description": "Digital operations shape public narratives abroad.",
        "branch": "diplomacy",
        "column": 6, "row": 10,
        "requires": ["dip_propaganda"],
        "cost": 170,
        "era_years": [(2000, 2060)],
        "icon": "🧠",
        "unlocks": {"prestige": 8, "war_support": 0.03},
        "unlock_text": "+8 Prestige  ·  +3% War Support",
    },

    {
        "id": "eco_tariffs",
        "name": "Protective Tariffs",
        "description": "Raise import duties to protect domestic industry.",
        "branch": "diplomacy",
        "column": 7, "row": 4,
        "requires": ["eco_banking"],
        "cost": 55,
        "era_years": [(1815, 2060)],
        "icon": "🧾",
        "unlocks": {"gdp_growth": 0.006, "trade_openness": -0.03},
        "unlock_text": "+0.6% GDP Growth  ·  −3% Trade Openness",
    },
    {
        "id": "eco_austerity_policy",
        "name": "Fiscal Austerity",
        "description": "Tight budgets curb inflation at social cost.",
        "branch": "diplomacy",
        "column": 7, "row": 5,
        "requires": ["eco_banking"],
        "cost": 70,
        "era_years": [(1930, 2060)],
        "icon": "✂️",
        "unlocks": {"inflation": -0.02, "happiness": -0.02},
        "unlock_text": "−2% Inflation  ·  −2% Happiness",
    },
    {
        "id": "eco_mega_projects",
        "name": "Mega Infrastructure Projects",
        "description": "Grand public works stimulate growth and employment.",
        "branch": "diplomacy",
        "column": 7, "row": 6,
        "requires": ["eco_keynesian"],
        "cost": 110,
        "era_years": [(1880, 2060)],
        "icon": "🏗️",
        "unlocks": {"gdp_growth": 0.012, "unemployment": -0.01},
        "unlock_text": "+1.2% GDP Growth  ·  −1% Unemployment",
    },
    {
        "id": "eco_global_finance",
        "name": "Global Finance",
        "description": "Capital markets integrate across borders.",
        "branch": "diplomacy",
        "column": 7, "row": 7,
        "requires": ["eco_globalisation"],
        "cost": 150,
        "era_years": [(1970, 2060)],
        "icon": "💹",
        "unlocks": {"gdp_growth": 0.012, "prestige": 6},
        "unlock_text": "+1.2% GDP Growth  ·  +6 Prestige",
    },
    {
        "id": "eco_supply_chain",
        "name": "Resilient Supply Chains",
        "description": "Diversified logistics reduce shocks.",
        "branch": "diplomacy",
        "column": 7, "row": 8,
        "requires": ["eco_globalisation"],
        "cost": 160,
        "era_years": [(1990, 2060)],
        "icon": "📦",
        "unlocks": {"stability": 0.02, "gdp_growth": 0.006},
        "unlock_text": "+2% Stability  ·  +0.6% GDP Growth",
    },
    {
        "id": "eco_digital_currency",
        "name": "Digital Currency",
        "description": "Digital settlement systems modernize finance.",
        "branch": "diplomacy",
        "column": 7, "row": 9,
        "requires": ["eco_global_finance"],
        "cost": 180,
        "era_years": [(2010, 2060)],
        "icon": "🪙",
        "unlocks": {"gdp_growth": 0.008, "prestige": 5},
        "unlock_text": "+0.8% GDP Growth  ·  +5 Prestige",
    },
    {
        "id": "eco_carbon_markets",
        "name": "Carbon Markets",
        "description": "Emissions trading shapes industrial policy.",
        "branch": "diplomacy",
        "column": 7, "row": 10,
        "requires": ["eco_globalisation"],
        "cost": 170,
        "era_years": [(2000, 2060)],
        "icon": "🌿",
        "unlocks": {"prestige": 6, "stability": 0.01},
        "unlock_text": "+6 Prestige  ·  +1% Stability",
    },
    {
        "id": "eco_mixed_economy",
        "name": "Mixed Economy",
        "description": "Balance market incentives with state direction.",
        "branch": "diplomacy",
        "column": 7, "row": 11,
        "requires": ["eco_banking"],
        "cost": 60,
        "era_years": [(1815, 2060)],
        "icon": "⚖️",
        "unlocks": {"gdp_growth": 0.006, "stability": 0.02},
        "unlock_text": "+0.6% GDP Growth  ·  +2% Stability",
    },
]

# ── Index for fast lookup ─────────────────────────────────────────────────────
_NODE_INDEX = {n["id"]: n for n in TECH_NODES}


def get_all_nodes(year: int | None = None) -> list[dict]:
    nodes = [_with_days(n) for n in TECH_NODES]
    if year is None:
        return nodes
    return [n for n in nodes if any(s <= year <= e for s, e in n.get("era_years", [(1815, 2060)]))]


def get_node(node_id: str) -> Optional[dict]:
    node = _NODE_INDEX.get(node_id)
    return _with_days(node) if node else None


def _infer_era_years(node_id: str) -> list[tuple[int, int]]:
    if node_id.startswith("air_") or node_id.startswith("arm_"):
        return [(1900, 2060)]
    if node_id.startswith("nav_"):
        return [(1815, 2060)]
    if node_id.startswith("res_"):
        return [(1890, 2060)]
    if node_id.startswith("dip_") or node_id.startswith("eco_"):
        return [(1815, 2060)]
    if node_id.startswith("ind_"):
        return [(1815, 2060)]
    return [(1815, 2060)]


def _with_days(node: Optional[dict]) -> Optional[dict]:
    if not node:
        return None
    if "days" in node:
        return node
    cost = node.get("cost", 60)
    node = {**node, "days": max(30, int(cost * 2))}
    node.setdefault("era_years", _infer_era_years(node.get("id", "")))
    return node


def can_research(node_id: str, researched_ids: set[str], year: int | None = None) -> tuple[bool, str]:
    """Return (can_research, reason). researched_ids is the set of already-completed node IDs."""
    node = _NODE_INDEX.get(node_id)
    if not node:
        return False, "Unknown technology"
    if year is not None:
        era_years = node.get("era_years", [(1815, 2060)])
        if not any(s <= year <= e for s, e in era_years):
            return False, "Unavailable in this era"
    if node_id in researched_ids:
        return False, "Already researched"
    missing = [r for r in node["requires"] if r not in researched_ids]
    if missing:
        missing_names = [_NODE_INDEX[m]["name"] for m in missing if m in _NODE_INDEX]
        return False, f"Requires: {', '.join(missing_names)}"
    return True, ""


def apply_node_unlocks(nation_data: dict, node: dict) -> dict:
    """
    Apply a node's unlock effects to a nation dict (same schema as game Nation model).
    Returns modified nation_data.
    """
    effects = node.get("unlocks", {})
    eco = nation_data.get("economy", {})
    mil = nation_data.get("military", {})

    for key, val in effects.items():
        if key == "research_slots":
            current = nation_data.get("research_slots_unlocked", 2)
            max_slots = nation_data.get("research_slots_max", 3)
            nation_data["research_slots_unlocked"] = min(max_slots, current + int(val))
            continue
        if key == "gdp_growth":
            eco["gdp_growth"] = min(0.15, eco.get("gdp_growth", 0.03) + val)
        elif key == "inflation":
            eco["inflation"] = max(0.0, eco.get("inflation", 0.02) + val)
        elif key == "unemployment":
            eco["unemployment"] = max(0.01, eco.get("unemployment", 0.07) + val)
        elif key == "trade_openness":
            eco["trade_openness"] = min(1.0, eco.get("trade_openness", 0.5) + val)
        elif key == "factories":
            eco["factories"] = eco.get("factories", 10) + int(val)
        elif key == "arms_factories":
            eco["arms_factories"] = eco.get("arms_factories", 3) + int(val)
        elif key == "research_labs":
            eco["research_labs"] = eco.get("research_labs", 1) + int(val)
        elif key == "morale":
            mil["morale"] = min(1.0, mil.get("morale", 0.8) + val)
        elif key == "equipment_level":
            mil["equipment_level"] = min(1.0, mil.get("equipment_level", 0.7) + val)
        elif key == "army_size":
            mil["army_size"] = mil.get("army_size", 100000) + int(val)
        elif key == "stability":
            nation_data["stability"] = min(1.0, nation_data.get("stability", 0.7) + val)
        elif key == "war_support":
            nation_data["war_support"] = min(1.0, nation_data.get("war_support", 0.5) + val)
        elif key == "prestige":
            nation_data["prestige"] = nation_data.get("prestige", 50) + val
        elif key == "happiness":
            nation_data["happiness"] = min(1.0, nation_data.get("happiness", 0.65) + val)
        elif key == "research_points":
            nation_data["research_points"] = nation_data.get("research_points", 0) + val

    nation_data["economy"] = eco
    nation_data["military"] = mil
    return nation_data
