// Auto-generated from ISO 3166-1 — do not edit manually
var COUNTRY_DATA = {
  nameToISO: {
    'afghanistan': 4,
    'african union': 566,
    'albania': 8,
    'algeria': 12,
    'america': 840,
    'american samoa': 16,
    'andorra': 20,
    'angola': 24,
    'anguilla': 660,
    'antarctica': 10,
    'antigua and barbuda': 28,
    'argentina': 32,
    'armenia': 51,
    'aruba': 533,
    'australia': 36,
    'austria': 40,
    'austria-hungary': 40,
    'austro-hungarian empire': 40,
    'azerbaijan': 31,
    'bahamas': 44,
    'bahrain': 48,
    'bangladesh': 50,
    'barbados': 52,
    'belarus': 112,
    'belgium': 56,
    'belize': 84,
    'benin': 204,
    'bermuda': 60,
    'bhutan': 64,
    'bolivia': 68,
    'bolivia, plurinational state of': 68,
    'bonaire, sint eustatius and saba': 535,
    'bosnia and herzegovina': 70,
    'botswana': 72,
    'bouvet island': 74,
    'brazil': 76,
    'britain': 826,
    'british india': 356,
    'british indian ocean territory': 86,
    'brunei darussalam': 96,
    'bulgaria': 100,
    'burkina faso': 854,
    'burma': 104,
    'burundi': 108,
    'byzantine empire': 300,
    'cabo verde': 132,
    'cambodia': 116,
    'cameroon': 120,
    'canada': 124,
    'cape verde': 132,
    'cayman islands': 136,
    'central african republic': 140,
    'chad': 148,
    'chile': 152,
    'china': 156,
    'chinese republic': 156,
    'christmas island': 162,
    'cocos (keeling) islands': 166,
    'colombia': 170,
    'comoros': 174,
    'confederacy': 840,
    'confederate states': 840,
    'congo': 180,
    'congo, democratic republic of the': 180,
    'cook islands': 184,
    'costa rica': 188,
    'croatia': 191,
    'cuba': 192,
    'curaã§ao': 531,
    'cyprus': 196,
    'czech republic': 203,
    'czechia': 203,
    'czechoslovakia': 203,
    'cã´te d\'ivoire': 384,
    'democratic republic of korea': 408,
    'denmark': 208,
    'djibouti': 262,
    'dominica': 212,
    'dominican republic': 214,
    'dprk': 408,
    'dr congo': 180,
    'east germany': 276,
    'east timor': 626,
    'ecuador': 218,
    'egypt': 818,
    'el salvador': 222,
    'england': 826,
    'equatorial guinea': 226,
    'eritrea': 232,
    'estonia': 233,
    'eswatini': 748,
    'ethiopia': 231,
    'european federation': 250,
    'falkland islands (malvinas)': 238,
    'faroe islands': 234,
    'fiji': 242,
    'finland': 246,
    'france': 250,
    'french empire': 250,
    'french guiana': 254,
    'french polynesia': 258,
    'french southern territories': 260,
    'gabon': 266,
    'gambia': 270,
    'georgia': 268,
    'german empire': 276,
    'germany': 276,
    'ghana': 288,
    'gibraltar': 292,
    'great britain': 826,
    'greece': 300,
    'greenland': 304,
    'grenada': 308,
    'guadeloupe': 312,
    'guam': 316,
    'guatemala': 320,
    'guernsey': 831,
    'guinea': 324,
    'guinea-bissau': 624,
    'guyana': 328,
    'haiti': 332,
    'heard island and mcdonald islands': 334,
    'holy see': 336,
    'honduras': 340,
    'hong kong': 344,
    'hungary': 348,
    'iceland': 352,
    'india': 356,
    'indonesia': 360,
    'iran': 364,
    'iran, islamic republic of': 364,
    'iraq': 368,
    'ireland': 372,
    'isle of man': 833,
    'israel': 376,
    'italian empire': 380,
    'italy': 380,
    'ivory coast': 384,
    'jamaica': 388,
    'japan': 392,
    'jersey': 832,
    'jordan': 400,
    'kazakhstan': 398,
    'kenya': 404,
    'kingdom of italy': 380,
    'kiribati': 296,
    'korea, democratic people\'s republic of': 408,
    'korea, republic of': 410,
    'kuwait': 414,
    'kyrgyzstan': 417,
    'lao people\'s democratic republic': 418,
    'laos': 418,
    'latvia': 428,
    'lebanon': 422,
    'lesotho': 426,
    'liberia': 430,
    'libya': 434,
    'liechtenstein': 438,
    'lithuania': 440,
    'luxembourg': 442,
    'macao': 446,
    'madagascar': 450,
    'malawi': 454,
    'malaysia': 458,
    'maldives': 462,
    'mali': 466,
    'malta': 470,
    'marshall islands': 584,
    'martinique': 474,
    'mauritania': 478,
    'mauritius': 480,
    'mayotte': 175,
    'mexico': 484,
    'micronesia': 583,
    'micronesia, federated states of': 583,
    'moldova': 498,
    'moldova, republic of': 498,
    'monaco': 492,
    'mongolia': 496,
    'montenegro': 499,
    'montserrat': 500,
    'morocco': 504,
    'mozambique': 508,
    'mughal empire': 356,
    'myanmar': 104,
    'namibia': 516,
    'nauru': 520,
    'nazi germany': 276,
    'nepal': 524,
    'netherlands, kingdom of the': 528,
    'new caledonia': 540,
    'new zealand': 554,
    'nicaragua': 558,
    'niger': 562,
    'nigeria': 566,
    'niue': 570,
    'norfolk island': 574,
    'north korea': 408,
    'north macedonia': 807,
    'north vietnam': 704,
    'northern mariana islands': 580,
    'norway': 578,
    'oman': 512,
    'ottoman empire': 792,
    'pakistan': 586,
    'palau': 585,
    'palestine, state of': 275,
    'panama': 591,
    'papua new guinea': 598,
    'paraguay': 600,
    'persian empire': 364,
    'peru': 604,
    'philippines': 608,
    'pitcairn': 612,
    'poland': 616,
    'portugal': 620,
    'prussia': 276,
    'puerto rico': 630,
    'qatar': 634,
    'qing dynasty': 156,
    'republic of china': 158,
    'republic of korea': 410,
    'romania': 642,
    'russia': 643,
    'russian empire': 643,
    'russian federation': 643,
    'rwanda': 646,
    'rã©union': 638,
    'saint barthã©lemy': 652,
    'saint helena, ascension and tristan da cunha': 654,
    'saint kitts and nevis': 659,
    'saint lucia': 662,
    'saint martin (french part)': 663,
    'saint pierre and miquelon': 666,
    'saint vincent and the grenadines': 670,
    'samoa': 882,
    'san marino': 674,
    'sao tome and principe': 678,
    'saudi arabia': 682,
    'senegal': 686,
    'serbia': 688,
    'seychelles': 690,
    'sierra leone': 694,
    'singapore': 702,
    'sint maarten (dutch part)': 534,
    'slovakia': 703,
    'slovenia': 705,
    'solomon islands': 90,
    'somalia': 706,
    'south africa': 710,
    'south georgia and the south sandwich islands': 239,
    'south korea': 410,
    'south sudan': 728,
    'south vietnam': 704,
    'soviet union': 643,
    'spain': 724,
    'sri lanka': 144,
    'sudan': 729,
    'suriname': 740,
    'svalbard and jan mayen': 744,
    'sweden': 752,
    'switzerland': 756,
    'syria': 760,
    'syrian arab republic': 760,
    'taiwan': 158,
    'taiwan, province of china': 158,
    'tajikistan': 762,
    'tanzania, united republic of': 834,
    'thailand': 764,
    'third reich': 276,
    'timor leste': 626,
    'timor-leste': 626,
    'togo': 768,
    'tokelau': 772,
    'tonga': 776,
    'trinidad and tobago': 780,
    'tunisia': 788,
    'turkey': 792,
    'turkmenistan': 795,
    'turks and caicos islands': 796,
    'tuvalu': 798,
    'tã¼rkiye': 792,
    'uae': 784,
    'uganda': 800,
    'uk': 826,
    'ukraine': 804,
    'united arab emirates': 784,
    'united kingdom': 826,
    'united kingdom of great britain and northern ireland': 826,
    'united states': 840,
    'united states minor outlying islands': 581,
    'united states of america': 840,
    'uruguay': 858,
    'usa': 840,
    'ussr': 643,
    'uzbekistan': 860,
    'vanuatu': 548,
    'venezuela, bolivarian republic of': 862,
    'viet nam': 704,
    'vietnam': 704,
    'virgin islands (british)': 92,
    'virgin islands (u.s.)': 850,
    'wallis and futuna': 876,
    'weimar republic': 276,
    'west germany': 276,
    'western sahara': 732,
    'yemen': 887,
    'yugoslavia': 688,
    'zambia': 894,
    'zimbabwe': 716,
    'ã…land islands': 248,
  },

  nameToAlpha2: {
    'afghanistan': 'af',
    'african union': 'ng',
    'albania': 'al',
    'algeria': 'dz',
    'america': 'us',
    'american samoa': 'as',
    'andorra': 'ad',
    'angola': 'ao',
    'anguilla': 'ai',
    'antarctica': 'aq',
    'antigua and barbuda': 'ag',
    'argentina': 'ar',
    'armenia': 'am',
    'aruba': 'aw',
    'australia': 'au',
    'austria': 'at',
    'austria-hungary': 'at',
    'austro-hungarian empire': 'at',
    'azerbaijan': 'az',
    'bahamas': 'bs',
    'bahrain': 'bh',
    'bangladesh': 'bd',
    'barbados': 'bb',
    'belarus': 'by',
    'belgium': 'be',
    'belize': 'bz',
    'benin': 'bj',
    'bermuda': 'bm',
    'bhutan': 'bt',
    'bolivia': 'bo',
    'bolivia, plurinational state of': 'bo',
    'bonaire, sint eustatius and saba': 'bq',
    'bosnia and herzegovina': 'ba',
    'botswana': 'bw',
    'bouvet island': 'bv',
    'brazil': 'br',
    'britain': 'gb',
    'british india': 'in',
    'british indian ocean territory': 'io',
    'brunei darussalam': 'bn',
    'bulgaria': 'bg',
    'burkina faso': 'bf',
    'burma': 'mm',
    'burundi': 'bi',
    'byzantine empire': 'gr',
    'cabo verde': 'cv',
    'cambodia': 'kh',
    'cameroon': 'cm',
    'canada': 'ca',
    'cape verde': 'cv',
    'cayman islands': 'ky',
    'central african republic': 'cf',
    'chad': 'td',
    'chile': 'cl',
    'china': 'cn',
    'chinese republic': 'cn',
    'christmas island': 'cx',
    'cocos (keeling) islands': 'cc',
    'colombia': 'co',
    'comoros': 'km',
    'confederacy': 'us',
    'confederate states': 'us',
    'congo': 'cd',
    'congo, democratic republic of the': 'cd',
    'cook islands': 'ck',
    'costa rica': 'cr',
    'croatia': 'hr',
    'cuba': 'cu',
    'curaã§ao': 'cw',
    'cyprus': 'cy',
    'czech republic': 'cz',
    'czechia': 'cz',
    'czechoslovakia': 'cz',
    'cã´te d\'ivoire': 'ci',
    'democratic republic of korea': 'kp',
    'denmark': 'dk',
    'djibouti': 'dj',
    'dominica': 'dm',
    'dominican republic': 'do',
    'dprk': 'kp',
    'dr congo': 'cd',
    'east germany': 'de',
    'east timor': 'tl',
    'ecuador': 'ec',
    'egypt': 'eg',
    'el salvador': 'sv',
    'england': 'gb',
    'equatorial guinea': 'gq',
    'eritrea': 'er',
    'estonia': 'ee',
    'eswatini': 'sz',
    'ethiopia': 'et',
    'european federation': 'fr',
    'falkland islands (malvinas)': 'fk',
    'faroe islands': 'fo',
    'fiji': 'fj',
    'finland': 'fi',
    'france': 'fr',
    'french empire': 'fr',
    'french guiana': 'gf',
    'french polynesia': 'pf',
    'french southern territories': 'tf',
    'gabon': 'ga',
    'gambia': 'gm',
    'georgia': 'ge',
    'german empire': 'de',
    'germany': 'de',
    'ghana': 'gh',
    'gibraltar': 'gi',
    'great britain': 'gb',
    'greece': 'gr',
    'greenland': 'gl',
    'grenada': 'gd',
    'guadeloupe': 'gp',
    'guam': 'gu',
    'guatemala': 'gt',
    'guernsey': 'gg',
    'guinea': 'gn',
    'guinea-bissau': 'gw',
    'guyana': 'gy',
    'haiti': 'ht',
    'heard island and mcdonald islands': 'hm',
    'holy see': 'va',
    'honduras': 'hn',
    'hong kong': 'hk',
    'hungary': 'hu',
    'iceland': 'is',
    'india': 'in',
    'indonesia': 'id',
    'iran': 'ir',
    'iran, islamic republic of': 'ir',
    'iraq': 'iq',
    'ireland': 'ie',
    'isle of man': 'im',
    'israel': 'il',
    'italian empire': 'it',
    'italy': 'it',
    'ivory coast': 'ci',
    'jamaica': 'jm',
    'japan': 'jp',
    'jersey': 'je',
    'jordan': 'jo',
    'kazakhstan': 'kz',
    'kenya': 'ke',
    'kingdom of italy': 'it',
    'kiribati': 'ki',
    'korea, democratic people\'s republic of': 'kp',
    'korea, republic of': 'kr',
    'kuwait': 'kw',
    'kyrgyzstan': 'kg',
    'lao people\'s democratic republic': 'la',
    'laos': 'la',
    'latvia': 'lv',
    'lebanon': 'lb',
    'lesotho': 'ls',
    'liberia': 'lr',
    'libya': 'ly',
    'liechtenstein': 'li',
    'lithuania': 'lt',
    'luxembourg': 'lu',
    'macao': 'mo',
    'madagascar': 'mg',
    'malawi': 'mw',
    'malaysia': 'my',
    'maldives': 'mv',
    'mali': 'ml',
    'malta': 'mt',
    'marshall islands': 'mh',
    'martinique': 'mq',
    'mauritania': 'mr',
    'mauritius': 'mu',
    'mayotte': 'yt',
    'mexico': 'mx',
    'micronesia': 'fm',
    'micronesia, federated states of': 'fm',
    'moldova': 'md',
    'moldova, republic of': 'md',
    'monaco': 'mc',
    'mongolia': 'mn',
    'montenegro': 'me',
    'montserrat': 'ms',
    'morocco': 'ma',
    'mozambique': 'mz',
    'mughal empire': 'in',
    'myanmar': 'mm',
    'namibia': 'na',
    'nauru': 'nr',
    'nazi germany': 'de',
    'nepal': 'np',
    'netherlands, kingdom of the': 'nl',
    'new caledonia': 'nc',
    'new zealand': 'nz',
    'nicaragua': 'ni',
    'niger': 'ne',
    'nigeria': 'ng',
    'niue': 'nu',
    'norfolk island': 'nf',
    'north korea': 'kp',
    'north macedonia': 'mk',
    'north vietnam': 'vn',
    'northern mariana islands': 'mp',
    'norway': 'no',
    'oman': 'om',
    'ottoman empire': 'tr',
    'pakistan': 'pk',
    'palau': 'pw',
    'palestine, state of': 'ps',
    'panama': 'pa',
    'papua new guinea': 'pg',
    'paraguay': 'py',
    'persian empire': 'ir',
    'peru': 'pe',
    'philippines': 'ph',
    'pitcairn': 'pn',
    'poland': 'pl',
    'portugal': 'pt',
    'prussia': 'de',
    'puerto rico': 'pr',
    'qatar': 'qa',
    'qing dynasty': 'cn',
    'republic of china': 'tw',
    'republic of korea': 'kr',
    'romania': 'ro',
    'russia': 'ru',
    'russian empire': 'ru',
    'russian federation': 'ru',
    'rwanda': 'rw',
    'rã©union': 're',
    'saint barthã©lemy': 'bl',
    'saint helena, ascension and tristan da cunha': 'sh',
    'saint kitts and nevis': 'kn',
    'saint lucia': 'lc',
    'saint martin (french part)': 'mf',
    'saint pierre and miquelon': 'pm',
    'saint vincent and the grenadines': 'vc',
    'samoa': 'ws',
    'san marino': 'sm',
    'sao tome and principe': 'st',
    'saudi arabia': 'sa',
    'senegal': 'sn',
    'serbia': 'rs',
    'seychelles': 'sc',
    'sierra leone': 'sl',
    'singapore': 'sg',
    'sint maarten (dutch part)': 'sx',
    'slovakia': 'sk',
    'slovenia': 'si',
    'solomon islands': 'sb',
    'somalia': 'so',
    'south africa': 'za',
    'south georgia and the south sandwich islands': 'gs',
    'south korea': 'kr',
    'south sudan': 'ss',
    'south vietnam': 'vn',
    'soviet union': 'ru',
    'spain': 'es',
    'sri lanka': 'lk',
    'sudan': 'sd',
    'suriname': 'sr',
    'svalbard and jan mayen': 'sj',
    'sweden': 'se',
    'switzerland': 'ch',
    'syria': 'sy',
    'syrian arab republic': 'sy',
    'taiwan': 'tw',
    'taiwan, province of china': 'tw',
    'tajikistan': 'tj',
    'tanzania, united republic of': 'tz',
    'thailand': 'th',
    'third reich': 'de',
    'timor leste': 'tl',
    'timor-leste': 'tl',
    'togo': 'tg',
    'tokelau': 'tk',
    'tonga': 'to',
    'trinidad and tobago': 'tt',
    'tunisia': 'tn',
    'turkey': 'tr',
    'turkmenistan': 'tm',
    'turks and caicos islands': 'tc',
    'tuvalu': 'tv',
    'tã¼rkiye': 'tr',
    'uae': 'ae',
    'uganda': 'ug',
    'uk': 'gb',
    'ukraine': 'ua',
    'united arab emirates': 'ae',
    'united kingdom': 'gb',
    'united kingdom of great britain and northern ireland': 'gb',
    'united states': 'us',
    'united states minor outlying islands': 'um',
    'united states of america': 'us',
    'uruguay': 'uy',
    'usa': 'us',
    'ussr': 'ru',
    'uzbekistan': 'uz',
    'vanuatu': 'vu',
    'venezuela, bolivarian republic of': 've',
    'viet nam': 'vn',
    'vietnam': 'vn',
    'virgin islands (british)': 'vg',
    'virgin islands (u.s.)': 'vi',
    'wallis and futuna': 'wf',
    'weimar republic': 'de',
    'west germany': 'de',
    'western sahara': 'eh',
    'yemen': 'ye',
    'yugoslavia': 'rs',
    'zambia': 'zm',
    'zimbabwe': 'zw',
    'ã…land islands': 'ax',
  },
};